# permissions for end users to edit programs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: program-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: omd-operator
    app.kubernetes.io/part-of: omd-operator
    app.kubernetes.io/managed-by: kustomize
  name: program-editor-role
rules:
- apiGroups:
  - omd.com
  resources:
  - programs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - omd.com
  resources:
  - programs/status
  verbs:
  - get
