# permissions for end users to view programs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: program-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: omd-operator
    app.kubernetes.io/part-of: omd-operator
    app.kubernetes.io/managed-by: kustomize
  name: program-viewer-role
rules:
- apiGroups:
  - omd.com
  resources:
  - programs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - omd.com
  resources:
  - programs/status
  verbs:
  - get
