apiVersion: omd.com/v1alpha1
kind: Program
metadata:
  labels:
    app.kubernetes.io/name: program
    app.kubernetes.io/instance: program-sample
    app.kubernetes.io/part-of: omd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: omd-operator
  name: program-sample
spec:
  app:
    container:
      name: nginx
      image: nginx:1.19.6
      ports:
        - name: http
          port: 80
          containerPort: 80
          protocol: TCP
    replicas: 1
    appType: server
  service:
    enabled: true
  serviceAccount:
    create: true
