apiVersion: omd.com/v1alpha1
kind: PreviewTemplate
metadata:
  labels:
    app.kubernetes.io/name: previewtemplate
    app.kubernetes.io/instance: previewtemplate-sample
    app.kubernetes.io/part-of: omd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: omd-operator
  name: previewtemplate-sample2
spec:
  template: |-
    - repositoryName: test
      branch: main
      spec:
        service:
          enabled: true
        serviceAccount:
          create: true
        app:
          container:
            name: nginx
            image: nginx:1.26.0
            ports:
              - name: http
                containerPort: {{.Port}}
                protocol: TCP
        deploy:
          server: https://kubernetes.default.svc
          branch: main
          path: demo-1
          repo: git@github.com:oh-my-deploy/omd-operator-example.git
